import { GoogleGenAI, Type } from "@google/genai";
import type { Handler } from 'aws-lambda';

const MODEL_NAME = "gemini-2.5-flash";

// Tax Research Document for AI context
const TAX_RESEARCH_DOCUMENT = `
NIGERIAN TAX LAW KNOWLEDGE BASE (Nigeria Tax Act 2025 Edition)
Legislative Baseline: Nigeria Tax Act 2025, Nigeria Tax Administration Act 2025
Effective Date: January 1, 2026

=== CORE POLICY CHANGES (2026 SHIFT) ===

PERSONAL INCOME TAX (PIT) REFORMS:
- Income ≤₦800,000/year: 100% Tax-Exempt (0% rate)
- Income ₦800k-₦3m: 15% marginal rate
- Income ₦3m-₦12m: 18% marginal rate
- Income ₦12m-₦25m: 21% marginal rate
- Income ₦25m-₦50m: 23% marginal rate
- Income >₦50m: 25% marginal rate (top rate)

CONSOLIDATED RELIEF ALLOWANCE (CRA) - ABOLISHED:
The old CRA (₦200,000 + 20% of gross income) is replaced by:
1. Rent Relief: Lower of ₦500,000 or 20% of actual annual rent paid (evidence required)
2. Pension contributions remain deductible (8% employee contribution)
3. NHF contributions remain deductible (2.5%)
4. Health Insurance premiums are deductible

COMPANIES INCOME TAX (CIT):
- Small Companies (turnover ≤₦50m): 0% CIT rate (must still file nil returns)
- Large Companies: 30% CIT rate
- Development Levy: 4% consolidated (replaces Education Tax 2.5%, NITDA 1%, NASENI 0.25%)
- Capital Gains Tax for companies: Increased from 10% to 30%

VALUE ADDED TAX (VAT):
- Rate: 7.5%
- Registration threshold: ₦25m turnover
- Input VAT: Now recoverable on ALL business purchases (services and assets included)
- Zero-rated: Basic food, medical products, educational materials, renewable energy equipment

=== APPROVED TAX COLLECTION JURISDICTIONS ===

FEDERAL GOVERNMENT (FIRS) ONLY:
1. Companies Income Tax (CIT)
2. Value Added Tax (VAT)
3. Petroleum Profits Tax
4. Capital Gains Tax (Companies & Abuja residents)
5. Stamp Duties (Corporate)
6. Development Levy (4%)

STATE GOVERNMENT (SIRS) ONLY:
1. Personal Income Tax (PAYE & Direct Assessment)
2. Withholding Tax (Individuals)
3. Capital Gains Tax (Individuals)
4. Stamp Duties (Individual instruments)
5. Road Taxes / Vehicle Licenses
6. Business Premises Registration (Urban: ₦10k max, Rural: ₦2k max)
7. Land Use Charge / Ground Rent

LOCAL GOVERNMENT (LGA) ONLY:
1. Shops and Kiosks Rates
2. Tenement Rates
3. Liquor License Fees
4. Slaughter Slab Fees
5. Registration fees (Marriage, Birth, Death)
6. Motor Park Levies (inside parks only)
7. Right of Occupancy Fees (Rural only)

ILLEGAL/NUISANCE TAXES: Bicycle Tax, Wheelbarrow Tax, Radio License (Local), roadblock collections

=== SECTOR-SPECIFIC RULES ===

DIGITAL ECONOMY / FREELANCERS / INFLUENCERS:
- Nigerian residents taxed on WORLDWIDE income (>183 days residence)
- Income from YouTube, Upwork, TikTok, etc. is taxable
- Individual content creators: Pay PIT to State (Direct Assessment)
- Incorporated brands: Pay CIT to FIRS
- Digital product sales to Nigerians: Charge 7.5% VAT if turnover >₦25m

INFORMAL SECTOR (Artisans, Market Traders):
- Fall under Presumptive Tax Regime
- State estimates tax based on trade/location
- States negotiate rates with trade unions
- One demand notice per year is normal
- Daily collections by "agberos" are often ILLEGAL

TRANSPORTERS (Okada, Keke, Taxi, Trucks):
- Road Taxes: Annual payment to State
- Daily Levies: Harmonized ₦200-₦800/day
- Inter-State: Single Inter-State Road Sticker (SIRTS) only
- Roadblocks for revenue collection are CRIMINAL OFFENSES

=== COMPLIANCE ESSENTIALS ===

TAX IDENTIFICATION NUMBER (TIN):
- Individuals: Auto-generated via BVN/NIN at tin.jtb.gov.ng
- Companies: Generated by CAC upon registration

OFFICIAL PAYMENT CHANNELS:
- Federal Taxes: TaxPro Max (taxpromax.firs.gov.ng) → Remita RRR
- State Taxes: State portals (etax.lirs.net, fctirs.gov.ng, etc.)
- NEVER pay cash to individuals
- Always demand Automated Revenue Receipt

KEY FILING DATES:
- PIT Filing: March 31 (annual)
- CIT Filing: June 30 (annual, 6 months after year end)
- VAT Remittance: 21st of each month

=== IMPORTANT THRESHOLDS ===

- PIT Exemption: ₦800,000 annual income
- Small Company: ₦50m turnover + ₦250m assets
- VAT Registration: ₦25m turnover
- Severance Tax-Free: Up to ₦50m (increased from ₦10m)
- Rent Relief Cap: ₦500,000 or 20% of rent (whichever is lower)
- CGT Share Exemption: Proceeds <₦150m in 12 months
`;

interface TaxProfile {
  persona: string;
  entityType: string;
  stateOfResidence: string;
  annualGrossIncome?: number;
  rentPaid?: number;
  preferredPolicy?: string;
  transactions?: Array<{ type: string; amount: number }>;
}

interface ConversationMessage {
  role: 'user' | 'assistant';
  text: string;
}

interface RequestBody {
  action: 'getTaxAdvice' | 'generateTips' | 'parseReceipt';
  payload: {
    profile?: TaxProfile;
    question?: string;
    conversationHistory?: ConversationMessage[];
    base64Image?: string;
  };
}

interface LambdaResponse {
  statusCode: number;
  headers: Record<string, string>;
  body: string;
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type,Authorization',
  'Access-Control-Allow-Methods': 'POST,OPTIONS',
  'Content-Type': 'application/json'
};

function buildSystemInstruction(profile: TaxProfile | null | undefined): string {
  const totalIncome = profile
    ? (profile.transactions?.filter(t => t.type === 'income').reduce((acc, curr) => acc + curr.amount, 0) || profile.annualGrossIncome || 0)
    : 0;

  return `
    You are Levy, a helpful Nigerian tax assistant powered by the LevyMate app.
    Your goal is to explain Nigerian tax laws in simple, friendly terms.

    === IMPORTANT BEHAVIOR ===
    - NEVER introduce yourself in responses. The user already knows who you are.
    - Go straight to answering the question without preamble.
    - Be smart about understanding tax-related questions. Questions like "Will I pay tax as a mechanic?", "Do tailors pay tax?", "What about Uber drivers?" ARE tax questions - answer them using the Informal Sector / Presumptive Tax information from the knowledge base.
    - Any question about whether someone pays tax, how much tax, tax rates, tax filing, etc. is a tax question - answer it helpfully.

    === TOPICS YOU HANDLE ===
    1. Nigerian tax laws and regulations (PIT, CIT, VAT, CGT, etc.)
    2. Tax for ANY profession or business type (use Informal Sector knowledge for artisans, traders, etc.)
    3. The LevyMate app features and how to use them
    4. Tax compliance, filing, and payment processes in Nigeria
    5. The Nigeria Tax Act 2025 and Finance Act 2020

    === OFF-TOPIC HANDLING ===
    Only decline questions that are clearly NOT about taxes or LevyMate (like "What's the weather?" or "Tell me a joke").
    For those, simply say: "That's outside my area! I'm here to help with Nigerian tax questions. What would you like to know about taxes?"

    ${profile ? `=== USER CONTEXT ===
    - Persona: ${profile.persona}
    - Entity Type: ${profile.entityType}
    - Annual Gross Est: ₦${totalIncome.toLocaleString()}
    - Rent Paid: ₦${(profile.rentPaid || 0).toLocaleString()}
    - State: ${profile.stateOfResidence}
    - Policy Year: ${profile.preferredPolicy === 'ACT_2026_PROPOSED' ? 'Nigeria Tax Act 2025 (Effective 2026)' : 'Finance Act 2020'}` : ''}

    === LEVYMATE APP KNOWLEDGE ===
    LevyMate is a Nigerian tax calculator app that helps individuals and businesses:

    FEATURES:
    - Tax Calculator: Calculate PAYE, CIT, and VAT based on both Finance Act 2020 and Nigeria Tax Act 2025
    - Income & Expense Tracking: Log income and expenses with categories
    - Receipt Scanning: OCR-powered receipt scanning for Pro users
    - AI Tax Assistant: Ask questions about Nigerian tax laws (that's me, Levy!)
    - Education Hub: Learn about tax laws with articles and explanations
    - Tax Comparison: Compare tax under old vs new Nigerian tax laws
    - VAT Input Credit: Track and optimize VAT recoveries
    - Compliance Calendar: Never miss filing deadlines

    PRICING:
    - Free Plan: Basic calculator, 50 transactions/month, 5 AI queries/day, Education Hub access
    - Pro Plan (₦2,999/month): Unlimited transactions, receipt scanning, CSV export, unlimited AI queries

    HOW TO USE:
    1. Create an account or use as guest
    2. Select your persona (employment type)
    3. Enter your income and expenses
    4. View calculated tax breakdown
    5. Use AI assistant for questions
    6. Export or save your tax records

    === KNOWLEDGE BASE ===
    Use the following verified research document as your PRIMARY and ONLY source of truth for tax information.
    NEVER make up tax rates, thresholds, or rules that are not in this document.
    If the answer is not in the document, say: "I don't have specific information about that in my knowledge base. Please consult FIRS or a tax professional."

    ${TAX_RESEARCH_DOCUMENT}

    === CONVERSATION STYLE ===
    - Be warm, friendly, and conversational - like a knowledgeable friend helping out
    - NEVER use markdown formatting like ** for bold, - for bullets, or # for headers
    - Write in plain, natural sentences and paragraphs like a human would in a chat
    - Use line breaks between paragraphs for readability
    - Use emojis sparingly to add warmth (1-2 per response max)
    - Go straight to the answer - no introductions or preamble
    - Ask follow-up questions when clarification would help
    - Use "you" and "your" to make it personal
    - Keep responses concise - aim for 2-4 short paragraphs max

    === FORMATTING RULES ===
    - NO dashes (-) for lists. Use numbers (1, 2, 3) or write in prose.
    - NO asterisks (**) for bold. Just write normally.
    - NO markdown at all. Write like you're texting a friend.
    - When listing items, use line breaks and numbers, or incorporate into sentences.

    === RESPONSE RULES ===
    1. Jump straight into the answer. No "Great question!" or "Sure!" openers.
    2. Use Naira (₦) for all currency amounts.
    3. Reference specific information from the knowledge base when relevant, but present it naturally.
    4. For state-specific questions, check the State-Specific section.
    5. DO NOT add disclaimers at the end of every message - the app already shows a permanent disclaimer.
    6. If the user asks about tax evasion, firmly but kindly explain that's illegal and could lead to serious penalties.
    7. Emphasize the difference between "Tax Optimization" (legal) and "Tax Evasion" (illegal) when relevant.
    8. If something is an ILLEGAL/NUISANCE TAX, tell them clearly and advise how to report it.
    9. When asked about LevyMate Pro plan or pricing, explain the features naturally and end your response with exactly: [SHOW_PRO_CARD]
    10. When asked about the Free plan, how to sign up, or creating a free account, explain the free features and end with exactly: [SHOW_FREE_CARD]
    11. For LevyMate app questions, explain the feature clearly and guide them on how to use it.
  `;
}

async function handleGetTaxAdvice(
  ai: GoogleGenAI,
  profile: TaxProfile | null | undefined,
  question: string,
  conversationHistory: ConversationMessage[] = []
): Promise<string> {
  const systemInstruction = buildSystemInstruction(profile);

  const contents = [
    ...conversationHistory.map(msg => ({
      role: msg.role === 'user' ? 'user' : 'model',
      parts: [{ text: msg.text }]
    })),
    { role: 'user', parts: [{ text: question }] }
  ];

  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: contents,
    config: {
      systemInstruction: systemInstruction,
      thinkingConfig: { thinkingBudget: 0 }
    }
  });

  return response.text || "I couldn't generate a response. Please try again.";
}

async function handleGenerateTips(ai: GoogleGenAI, profile: TaxProfile): Promise<string> {
  const totalIncome = profile.transactions?.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0) || profile.annualGrossIncome || 0;

  const prompt = `
    Generate 3 specific, legal tax-saving or financial health tips for a Nigerian ${profile.persona}
    earning approximately ₦${totalIncome.toLocaleString()} annually.
    Format as a simple bulleted list.
  `;

  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: prompt,
  });

  return response.text || "Check your pension contributions to optimize tax relief.";
}

async function handleParseReceipt(ai: GoogleGenAI, base64Image: string): Promise<object> {
  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: "image/jpeg",
            data: base64Image
          }
        },
        {
          text: "Extract the following from this receipt image: Total Amount (number only), Date (YYYY-MM-DD), Merchant Name (as description), and a Category (e.g., Supplies, Food, Utilities). Respond in JSON format."
        }
      ]
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          amount: { type: Type.NUMBER },
          date: { type: Type.STRING },
          description: { type: Type.STRING },
          category: { type: Type.STRING }
        }
      }
    }
  });

  if (response.text) {
    const data = JSON.parse(response.text);
    return {
      amount: data.amount,
      date: data.date,
      description: data.description,
      category: data.category,
      type: 'expense',
      source: 'ocr'
    };
  }
  throw new Error("No data extracted from receipt");
}

export const handler: Handler = async (event): Promise<LambdaResponse> => {
  // Handle CORS preflight
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: corsHeaders,
      body: ''
    };
  }

  // Validate API key
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return {
      statusCode: 500,
      headers: corsHeaders,
      body: JSON.stringify({ error: 'AI service not configured' })
    };
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const body: RequestBody = JSON.parse(event.body || '{}');

    let result: string | object;

    switch (body.action) {
      case 'getTaxAdvice':
        if (!body.payload.question) {
          return {
            statusCode: 400,
            headers: corsHeaders,
            body: JSON.stringify({ error: 'Question is required' })
          };
        }
        result = await handleGetTaxAdvice(
          ai,
          body.payload.profile,
          body.payload.question,
          body.payload.conversationHistory
        );
        break;

      case 'generateTips':
        if (!body.payload.profile) {
          return {
            statusCode: 400,
            headers: corsHeaders,
            body: JSON.stringify({ error: 'Profile is required' })
          };
        }
        result = await handleGenerateTips(ai, body.payload.profile);
        break;

      case 'parseReceipt':
        if (!body.payload.base64Image) {
          return {
            statusCode: 400,
            headers: corsHeaders,
            body: JSON.stringify({ error: 'Image is required' })
          };
        }
        result = await handleParseReceipt(ai, body.payload.base64Image);
        break;

      default:
        return {
          statusCode: 400,
          headers: corsHeaders,
          body: JSON.stringify({ error: 'Invalid action' })
        };
    }

    return {
      statusCode: 200,
      headers: corsHeaders,
      body: JSON.stringify({ result })
    };

  } catch (error) {
    console.error('Gemini Proxy Error:', error);
    return {
      statusCode: 500,
      headers: corsHeaders,
      body: JSON.stringify({
        error: 'AI service error',
        message: error instanceof Error ? error.message : 'Unknown error'
      })
    };
  }
};
